apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: SixApi
namespace: production
bases:
  - ../../base
commonAnnotations:
  app: SixApi
  backstage.io/kubernetes-id: "SixApi"
commonLabels:
  app: SixApi
  backstage.io/kubernetes-id: "SixApi"
patchesStrategicMerge:
  - configmap_patch.yaml
  - deployment_patch.yaml